// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://linxpynrwpqokugizynm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbnhweW5yd3Bxb2t1Z2l6eW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDYzODUsImV4cCI6MjA2NTQ4MjM4NX0.9CbrT2Q3TZWrQKwNgw-6wYgIfbsNx-YKmI0js08ASYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);